### ISSUE TITLE
Interval for data refresh to low

### ISSUE THREAD

**Issue by simowNgithub** [kodebach/hacs-idm-heatpump#16]
Manufacturer defaults for reading and writing data are 60 seconds. At the moment there is a default set by 30.

Lower values can break the display controller and is not supported. 

(told me my idm service partner)

**Comment by kodebach** [comment]
Thanks for reporting the issue. I increased the default interval to 300 seconds to be safe.

**Comment by tschweitzer** [comment]
Is this issue/limitation still true? Is there any documentation or other reports that confirm the risk of breaking the display controller?

**Comment by kodebach** [comment]
Since [v0.11.0](https://github.com/kodebach/hacs-idm-heatpump/releases/tag/v0.11.0) faster refresh intervals are allowed, but a warning is displayed and you need to check a box to acknowledge it.

I still doubt it would actually physically break the controller, it's probably a misunderstanding and it just creates high load on the controller which causes it to lag/freeze or be otherwise unresponsive.

The ideal solution would probably be different intervals for different registers, so that we're not requesting as much data (measured temperature values will change often, but things like selected heating mode doesn't). But I don't have the time to implement that.
