### ISSUE TITLE
Download and installed - nothing happens - Modbus Außetemperatur works via Yaml 

### ISSUE THREAD

**Issue by KKlausl** [kodebach/hacs-idm-heatpump#26]
Sorry for bothering you, cause I am a newbee here. 

Im coming from Openhab where I integrated a bunch of IDM - Modbus values with modbus bindung. 

Now, with homeassistant I managed to integrate "Außentemperatur" and other Modbus - registers via config.yaml. 

after downloading and installing your integration and following the steps you prescribe, I cant find any values or entities. And there is no UI to define stuff. Can u help me?

**Comment by kodebach** [comment]
If you just followed the README and then stopped, you probably haven't actually configured the integration yet. Since you're new and coming from openHAB you probably didn't know that's necessary. I didn't include this final step in the README, because it's the same for all integrations (custom ones, and the ones included with Home Assistant).

Theoretically, this link should ask you for your (local) Home Assistant URL and then link you to the correct page in Home Assistant: https://my.home-assistant.io/redirect/config_flow_start/?domain=idm_heatpump

Otherwise:
1. Open your Home Assistant page manually and then go to "Settings" -> "Devices & Services".
2. Click the "Add Integration" button in the bottom right corner.
3. Search for and select "IDM heat pump" and complete the setup steps.

**Comment by KKlausl** [comment]
Oh my... you are correct, i feel embarrassed... Thank you very much for that "hint"!! 
well, the advantage is: I have your attention, cause the UI tells me, the IP adress is not correct. ("Heat pump not found at given hostname/ip") - but this is the same IP which I use to listen to AußentemperaturIDM through Modbus via config.yaml and this works fine:

`modbus:
  - name: idm_lwp
    type: tcp
    host: 192.168.0.23
    port: 502
    sensors:
      - name: Keller (IDM)
        slave: 1
        scale: 1
        offset: 0
        unit_of_measurement: °C
        address: 1000
        input_type: input
        data_type: float32
        scan_interval: 10
        count: 2
        precision: 1
        swap: word`  

Is it possible that I make another newbee-mistake? :-/

**Comment by kodebach** [comment]
No that error basically means that the Modbus connection couldn't be established. Did you try removing the Modbus config from `config.yaml`?

AFAIK it should be possible to have multiple clients connect to the same Modbus server. But the IDM heat pump also disconnects rather frequently and randomly (which is why this integration has a few hacky workarounds), so maybe it also doesn't like simultaneous connections.

**Comment by KKlausl** [comment]
Hey, thank you again for your patience and your time! :)
I removed the modbus part out of config - the idm sensors stopped working - but the connection still could not be established. can I try something else or provide some information?

**Comment by kodebach** [comment]
Not sure what could be going wrong... But I did notice that the Modbus integration uses a newer version of `pymodbus`. I upgraded the version in this integration and made a new release. Please update (you should see the update in the HACS tab of your Home Assistant) and then try again.

**Comment by kodebach** [comment]
> Is it possible, that my IDM piump (ILM Terra HGL, Navigator 1.7) does not have this register? I have a modbus documentation from IDM, and that register is not mentioned. 

Well, if you have the documentation from IDM and the register isn't there, then that's probably correct. I only tested this integration with Navigator 2.0, so maybe the register was only added in the newer version.

This may also be the reason the integration isn't working for you. Maybe Navigator 1.7 is slightly different and incompatible with the way the integration tries to connect.

> I do not get sensful data. [...] Could you help me here?

In your config snippet, you have configured the register with `data_type: uint32`. I think you need to change that to `data_type: uint16`. Otherwise, the modbus library will read the next 16-bit register as well and combine both registers into a non-sensical 32-bit number.

As for mapping the integer values to names. The IDM documentation should state which integer means what (seems to be different for Navigator 1.7 too, since in this integration the values are 0, 1, 2). For the actual mapping, I'm afraid I can't really help you, since I haven't used the plain modbus integration much. Maybe there is a way to map the values directly, maybe you need to add a second template sensor to do the mapping. I'm sure someone on the [Home Assistant forum](https://community.home-assistant.io/) will be able to help you there.

**Comment by KKlausl** [comment]
Thank you for all your help! I managed to fix the „Betriebsart“ - different adress did the trick. :)

**Comment by kodebach** [comment]
I checked some stuff and it seems Navigator 1.7 and Navigator 2.0 use different Modbus interfaces. I clarified in the README that this integration only supports Navigator 2.0

**Comment by KKlausl** [comment]
Thank you again!
