### ISSUE TITLE
IP Adress not found

### ISSUE THREAD

**Issue by NaServas** [kodebach/hacs-idm-heatpump#7]
At first, thanks for developping the integration! Unfortunately, I am not able to use it.

After installing the Integration (V0.2.0 on HomeAssistant  2023.4.6 on a Raspberry Pi 3) as described in the github and starting the configuration in the UI, the heat pump's IP adress can not be found in the network, altough it its web interface is reachable from the browser.

**Comment by kodebach** [comment]
You need to make sure that the "Modbus TCP" is enabled on your heat pump. Googling for "idm navigator 2.0 modbus" should get you on the right path. You may need to ask your heat pump installer or IDM technical support to help you enable it, since the setting is hidden in a service menu. Only "Modbus TCP" needs to be enable, none of the more advanced settings are necessary.

**Comment by NaServas** [comment]
Thank you very much for the prompt supply and help, I'll contact the support the idm support.
